TEST:
  - VAR_TGT_DB: DEV_HAOYUAN
  - VAR_TGT_SCHEMA: DATA_QUALITY_STG
  - VAR_TGT_TBL: EE_CLIENT_FEATURE

ENV:
  - PROD_ENV_SFTP: # PROD_SFTP_SVR
  - PROD_ENV_ETL: # PROD_ETL_SVR
  - DEV_ENV: DEV-DB
  - DEV_ENV_IC: # change this to your DEV DB for testing purposes
    - AARON: DEV_AARON 
    - MILI: DEV_MILI 
    - HAOYUAN: DEV_HAOYUAN 

RELEASE_MANAGER:
  - RM_NM: # ADMIN
  - RM_EMAIL: # admin@uhtasi.org

# Thingking about 
EE:
  - 

CP:
  - 
  
TP:
  - 